services:
  db:
    container_name: db_ecommerce
    image: postgres:alpine
    environment:
      POSTGRES_USER : "admin"
      POSTGRES_DB : "db_ecommerce"
      POSTGRES_PASSWORD : "admin"
    ports:
      - 5432:5432