services:
  db:
    container_name: db_ecommerce
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER : ${DB_USER}
      POSTGRES_DB : ${DB}
      POSTGRES_PASSWORD : ${DB_PASSWORD}
    ports:
      - 5432:5432